SHELL:=/bin/bash

all: entropia_tiempo.png entropia_tamaño.png

%.x: %.o entropy.o functions.o
	g++ $^ -o $@

%.o: %.cpp
	g++ -c $<

%.txt: %.x
	./entropy.x

entropia_tiempo.png: entropy.py entropy.txt
	python entropy.py


tamaño_tiempo.png: entropy.py drop_size.txt
	python entropy.py

clean:
	rm -f *.o *.x *.png entropy.txt drop_size.txt